export const Types = {
  SEARCH_PRODUCTS: 'SEARCH_PRODUCTS',
  SEARCH_PRODUCTS_BY_CATEGORY: 'SEARCH_PRODUCTS_BY_CATEGORY',
  ORDER_PRODUCTS_DESC: 'ORDER_PRODUCTS_DESC',
  ORDER_PRODUCTS_ASC: 'ORDER_PRODUCTS_ASC',
};
