export const Types = {
  GET_PRODUCTS: "GET_PRODUCTS",
  ADD_NEW_PRODUCT: "ADD_NEW_PRODUCT",
  DELETE_PRODUCT: "DELETE_PRODUCT",
  EDIT_PRODUCT: "EDIT_PRODUCT",
  ERROR_REQUEST: "ERROR_REQUEST",
  GET_SINGLE_PRODUCT: "GET_SINGLE_PRODUCT",
};
