export const Types = {
  ADD_USER: "ADD_USER",
  ADD_USER_SUCCESS: "ADD_USER_SUCCESS",
  ADD_USER_FAIL: "ADD_USER_FAIL",
  SUCCESS_LOGIN: "SUCCESS_LOGIN",
  LOGIN_ERROR: "LOGIN_ERROR",
  LOGIN_FAIL: "LOGIN_FAIL",
  LOGOUT_USER: "LOGOUT",
};
