export const Types = {
  SHOPPING_LIST: 'SHOPPING_LIST',
  ADD_PRODUCT_TO_LIST: 'ADD_PRODUCT_TO_LIST',
  INCREMENT_PRODUCT_IN_LIST: 'INCREMENT_PRODUCT_IN_LIST',
  DECREMENT_PRODUCTS_IN_LIST: 'DECREMENT_PRODUCTS_IN_LIST',
  DELETE_PRODUCT_FROM_LIST: 'DELETE_PRODUCT_FROM_LIST',
  TOGGLE_SHOPPING_CARD: 'TOGGLE_SHOPPING_CARD',
  FINAL_SHOPPING_PRICE: 'FINAL_SHOPPING_PRICE',
  REDUCE_PRICE_WITH_VOUCHER: 'REDUCE_PRICE_WITH_VOUCHER',
  REDUCE_PRICE_WITH_DELIVERY_TYPE: 'REDUCE_PRICE_WITH_DELIVERY_TYPE',
  CLEAN_BASKET: 'CLEAN_BASKET',
};
